#include <rerun.hpp>

int main() {
    rerun::spawn().throw_on_failure();
}
